services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=colonial_DB'
      - 'POSTGRES_PASSWORD=constantino123'
      - 'POSTGRES_USER=william'
    ports:
      - '5460:5432'
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
